[bitnami/clickhouse] Fix volumePermissions's command syntax and security context (#16245)
* [bitnami/clickhouse] Fix volumePermissions command

The command used in `volumePermissions` init container was specified as string instead of a list of strings. This may have resulted in errors reported by Helm:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.initContainers[0].command): invalid type for io.k8s.api.core.v1.Container.command: got "string", expected "array"
```

Signed-off-by: Serge Tkatchouk <sp1j3t@gmail.com>

* [bitnami/clickhouse] Bump chart version to v3.3.2

Signed-off-by: Serge Tkatchouk <sp1j3t@gmail.com>

* [bitnami/clickhouse] Use own SecurityContext for volumePermissions

Signed-off-by: Serge Tkatchouk <sp1j3t@gmail.com>

* [bitnami/clickhouse] Render whole volumePermissions securityContext

Signed-off-by: Serge Tkatchouk <sp1j3t@gmail.com>

* [bitnami/clickhouse] Use tpl helper for volumePermissions SC

Signed-off-by: Serge Tkatchouk <sp1j3t@gmail.com>

* [bitnami/clickhouse] Remove unneeded mount in volumePermissions

Signed-off-by: Serge Tkatchouk <sp1j3t@gmail.com>

---------

Signed-off-by: Serge Tkatchouk <sp1j3t@gmail.com>