Fix if statement
CI/CD was failing because:
```
Error: parse error at (airflow/templates/statefulset-worker.yaml:12): function “Values” not defined
```