[bitnami/airflow] add podManagementPolicy support for workers (#2420)
* airflow: add podManagementPolicy support for workers

* [bitnami/airflow]: add podManagementPolicy to values files

* Fix if statement

CI/CD was failing because:
```
Error: parse error at (airflow/templates/statefulset-worker.yaml:12): function “Values” not defined
```

* [bitnami/airflow]: fix incorrect if statement

* Update values-production.yaml

* Update values.yaml

* [bitnami/airflow] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

Co-authored-by: Carlos Rodríguez Hernández <carlosrh@vmware.com>
Co-authored-by: Bitnami Containers <containers@bitnami.com>